[package]
name = "redis_rawl"
version = "0.1.20240915"
authors = ["raul gherman <raul.gherman@protonmail.com>"]
edition = "2021"
description = """
Minimal Redis client library implementation.
Forked from redis-raw `git@github.com:aminroosta/redis-raw-rs.git`"""
readme = "README.md"
license = "BSD-3-Clause"
documentation = "https://docs.rs/redis_rawl"
homepage = "https://github.com/raul-gherman/redis-rawl"
repository = "https://github.com/raul-gherman/redis-rawl"

[dependencies]
tokio = { version = "1.40.0", features = [
    "io-util",
    "net",
] }
thiserror = "1.0"
