[package]
name = "redis_rawl"
version = "0.0.1"
authors = ["raul gherman <raul.gherman@protonmail.com>"]
edition = "2021"
description = "Minimal Redis client library implementation."
readme = "README.md"
license = "BSD-3-Clause"
documentation = "https://docs.rs/redis_raw"
homepage = "https://github.com/raul-gherman/redis-rawl"
repository = "https://github.com/raul-gherman/redis-rawl"

[dependencies]
tokio = { version = "1.39.3", features = [
    # "fs",
    "io-util",
    # "io-std",
    "macros",
    "net",
    # "parking_lot",
    # "process",
    # "rt",
    "rt-multi-thread",
    # "signal",
    # "sync",
    # "time",
] }
thiserror = "1.0"
